# Travis CI configuration file.

language: php

php:
    - 5.6
    - 7.0

before_script:
    - composer install

script:
    - vendor/bin/codecept run unit --coverage-clover=clover.xml

after_success:
    - travis_retry php vendor/bin/coveralls -x clover.xml
